name: shop-app

services:
  db:
   image: mysql
  #  container_name: db
   command: --default-authentication-plugin=mysql_native_password
   env_file:
    ./.mysql.env
   restart: always
   volumes:
     - data:/var/lib/mysql

  webapp:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    # container_name: webapp
    volumes:
      - type: bind
        source: ./
        target: /app
    env_file:
     ./.env
    ports:
      - 3000:3000
volumes:
  data: